export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const MARK_AS_NOT_LOGGED = 'MARK_AS_NOT_LOGGED';

export const ACCEPT_INVITATION_REQUEST = 'ACCEPT_INVITATION_REQUEST';
export const ACCEPT_INVITATION_SUCCESS = 'ACCEPT_INVITATION_SUCCESS';
export const ACCEPT_INVITATION_FAILURE = 'ACCEPT_INVITATION_FAILURE';

export const REQUEST_ELEMENTS_REQUEST = 'REQUEST_ELEMENTS_REQUEST';
export const REQUEST_ELEMENTS_SUCCESS = 'REQUEST_ELEMENTS_SUCCESS';
export const REQUEST_ELEMENTS_FAILURE = 'REQUEST_ELEMENTS_FAILURE';
